### ISSUE TITLE
possible bug in `HTMLdecode` function

### ISSUE THREAD

**Issue by fangzhou-xie** [enricoschumann/textutils#3]
Thanks for this package! As I was testing some HTML symbols to decode, I have the following example that doesn't seem to be working as expected:

```
> textutils::HTMLdecode("&notin;")
[1] "¬in;"
> xml2::xml_text(xml2::read_html(paste0("<x>", "&notin;", "</x>")))
[1] "∉"
```

According to [here](https://www.freeformatter.com/html-entities.html#misc-html-entities) and [here](https://dev.w3.org/html5/html-author/charref), this symbol should be a mathematical "not in" operator, but when using `HTMLdecode` function, it returns something else. (Logically speaking, this is still "not in", but maybe not the one we want to use in this case ;)

Also I have used `xml2` package for comparison.

**Comment by enricoschumann** [comment]
That is a bug; thank you for the report. It happened because `&not` (without the semicolon) is also allowed in the [standard](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references) as an entity. It should be fixed now in the version on GitHub  [(commit)](https://github.com/enricoschumann/textutils/commit/4c4963b48993cb82c97122c204e945a49da1cc3f) and also in the version at http://enricoschumann.net/R/packages/textutils/ .

Would you give it a try, please? Again, thank you for the report.

**Comment by fangzhou-xie** [comment]
Thank you so much! I can confirm that this one is fixed (by installing the development version).
